defaultEntryPoints = ["https"]

[entryPoints]
    [entryPoints.https]
    address = ":4000"

[api]
insecure = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false
  network = "gateway"

[accessLog]
  filePath = "/var/log/access.log"
  format = "json"
